{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "wb.fullname" . -}}
{{- $servicePort := .Values.service.externalPort -}}
{{- $ingressPaths := .Values.ingress.paths -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "wb.fullname" . }}
  labels:
    app: {{ template "wb.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- if .Values.maintenance.enabled }}
    {{- $serviceName := include "maintenance.fullname" . -}}
    {{- $servicePort := .Values.maintenance.service.externalPort -}}
    {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          {{- range $ingressPaths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
          {{- end -}}
    {{- end -}}
    {{- else -}}
    {{- $serviceName := include "wb.fullname" . -}}
    {{- $servicePort := .Values.service.externalPort -}}
    {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          {{- range $ingressPaths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
          {{- end -}}
    {{- end -}}
    {{- end -}}
  {{- if (or .Values.ingress.tls .Values.certificate.enabled) }}
  tls:
    {{- if .Values.ingress.tls }}
    {{- toYaml .Values.ingress.tls | nindent 4 }}
    {{- end -}}
    {{- if .Values.certificate.enabled }}
    - secretName: {{ include "wb.fullname" . }}
      hosts:
        {{- range .Values.certificate.dnsNames }}
        - {{ . }}
        {{- end -}}
    {{- end -}}
  {{- end -}}
{{- end -}}
